apiVersion: apps/v1
kind: Deployment
metadata:
  name: churn-api-deployment
  namespace: default   # 👈 यह अब बिल्कुल सही जगह पर (metadata के अंदर) है
  labels:
    app: churn-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: churn-api
  template:
    metadata:
      labels:
        app: churn-api
    spec:
      containers:
      - name: churn-api-container
        image: sudhirmahaseth/customer-churn-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "250m"
            memory: "512Mi"